# terraform.yml

name: 'Terraform CI/CD'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless of OS
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the code from the repo
    - name: Checkout
      uses: actions/checkout@v3

    # Set up Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Initialize Terraform project
    - name: Terraform Init
      id: init
      run: terraform init

    # Plan the infrastructure changes
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color

    # Apply the changes if it's a pull request to the main branch
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve
